name: Savant-RS Manylinux Python

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags: [ 'v*.*.*', '*.*.*' ]
  workflow_dispatch:

permissions: write-all

jobs:

  protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload protobuf
        uses: actions/upload-artifact@v4
        with:
          name: savant_rs.proto
          path: savant_protobuf/src/savant_rs.proto

  build:
    strategy:
      matrix:
        include:
          - name: manylinux-arm
            arch: linux/arm64
            label: arm64
            group: native-builders-arm
          - name: manylinux-x86
            arch: linux/amd64
            label: x86
            group: native-builders-x86

    timeout-minutes: 600
    runs-on:
      group: ${{ matrix.group }}
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.manylinux
          platforms: ${{ matrix.arch }}
          tags: savant-rs
          push: false
          load: true
          context: .
          build-args: |
            PYTHON_INTERPRETER=3.8 3.9 3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.10 pypy3.11

      - name: Copy wheels
        run: docker run --rm -v $(pwd)/distfiles:/tmp savant-rs cp -R /opt/dist /tmp

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.label }}
          path: distfiles/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build, protobuf ]
    steps:
      - name: Make directory for download
        run: mkdir -p artifacts
      - name: Clean up old wheels
        run: rm -rf artifacts/*.whl
      - name: Clean up old protobuf files
        run: rm -rf artifacts/*.proto
      - uses: actions/download-artifact@v4
        with:
          name: savant_rs.proto
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: wheels-x86
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: wheels-arm64
          path: artifacts
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
