name: Savant Platform-Specific Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:

  build:
    strategy:
      matrix:
        include:
          - name: savant-wheels-arm
            arch: linux/arm64
            label: arm64
            group: native-builders-arm
          - name: savant-wheels-x86
            arch: linux/amd64
            label: x86
            group: native-builders-x86

    timeout-minutes: 600
    runs-on:
      group: ${{ matrix.group }}
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.savant-wheels
          platforms: ${{ matrix.arch }}
          tags: savant-wheels
          push: false
          load: true
          context: .

      - name: Copy wheels
        run: docker run --rm -v $(pwd)/distfiles:/tmp savant-wheels cp -R /opt/dist /tmp

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: savant-wheels-${{ matrix.label }}
          path: distfiles/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Make directory for download
        run: mkdir -p artifacts
      - name: Clean up old wheels
        run: rm -rf artifacts/*.whl
      - uses: actions/download-artifact@v4
        with:
          name: savant-wheels-x86
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: savant-wheels-arm64
          path: artifacts
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
